# Copyright (c) 2018 Adam Kowalski
# This code is available under the "Apache License 2.0"
# Please see the file COPYING in this distribution for license terms.

version: '3'
services:
    data-downloader:
        image: adamkowalski/python
        volumes:
            - ../data/:/data/
            - ./:/data-downloader/
        command: bash /data-downloader/data-downloader.sh
