# Copyright (c) 2018 Adam Kowalski
# This code is available under the "Apache License 2.0"
# Please see the file COPYING in this distribution for license terms.

version: '2.3'
services:
    data-labeler:
        image: adamkowalski/python
        volumes:
            - ../data/:/data/
            - ./:/data-partitioner/
            - ../.emacs.d/:/root/.emacs.d/
        working_dir: /data-partitioner
        runtime: nvidia
        command: python data-partitioner.py
