version: '2.3'
services:
    frontend:
        image: adamkowalski/typescript
        volumes:
            - ./frontend/:/frontend/
            - ../.emacs.d/:/root/.emacs.d/
        stdin_open: true
        tty: true
        working_dir: /frontend
        ports:
            - "8888:8888"
        networks:
            - webapp
        command: bash

    model-saver:
        image: adamkowalski/python
        volumes:
            - ./model-saver/:/model-saver/
            - ../.emacs.d/:/root/.emacs.d/
            - ./models/:/models/
            - ../data/:/data/
            - ./library/:/library/
        stdin_open: true
        tty: true
        working_dir: /model-saver
        networks:
            - webapp
        environment:
            - PYTHONPATH=/library/:$PYTHONPATH
        runtime: nvidia
        command: python model_saver.py


    model-runner:
        image: adamkowalski/python
        volumes:
            - ./model-runner/:/model-runner/
            - ../.emacs.d/:/root/.emacs.d/
            - ./models/:/models/
            - ../data/:/data/
            - ./library/:/library/
        stdin_open: true
        tty: true
        working_dir: /model-runner
        networks:
            - webapp
        environment:
            - PYTHONPATH=/library/:$PYTHONPATH
        runtime: nvidia
        command: bash

    model-loader:
        image: adamkowalski/python
        volumes:
            - ./model-loader/:/model-loader/
            - ../.emacs.d/:/root/.emacs.d/
            - ./models/:/models/
            - ./library/:/library/
        stdin_open: true
        tty: true
        working_dir: /model-loader
        networks:
            - webapp
        environment:
            - PYTHONPATH=/library/:$PYTHONPATH
        runtime: nvidia
        command: bash

networks:
    webapp:

