version: '2.3'
services:
    frontend:
        image: adamkowalski/typescript
        volumes:
            - ./frontend/:/frontend/
            - ../.emacs.d/:/root/.emacs.d/
        stdin_open: true
        tty: true
        working_dir: /frontend
        ports:
            - "8888:8888"
        networks:
            - webapp
        command: bash

    model-saver:
        image: adamkowalski/python
        volumes:
            - ./model-saver/:/model-saver/
            - ../.emacs.d/:/root/.emacs.d/
        stdin_open: true
        tty: true
        working_dir: /model-saver
        networks:
            - webapp
        command: bash

networks:
    webapp:

